#!/bin/bash

#command-info: build index for the easy-presenter

source "$TERMINAL_PATH/app.bootstrap"

index_file_presentations="$EASY_PRESENTER_SOURCE/index.md"
readme_file_presentations="$EASY_PRESENTER_SOURCE/README.md"
parent_folder='.'
depth=0

file_clear "$index_file_presentations"
file_clear "$readme_file_presentations"

index_file_init "$readme_file_presentations" "Presentations:"

for presentations_path in "$EASY_PRESENTER_SOURCE"/*
do
  # if it is a file
  if [ -f "$presentations_path" ];
  then
    continue
  fi

  presentations_path_relative=$(basename "$presentations_path")

  possible_presentation_teaser_file="$presentations_path/00_index/00_teaser.md"
  if [ -f "$possible_presentation_teaser_file" ];
  then
    presentation_name=$(index_name_from_file "$possible_presentation_teaser_file")
  else
    presentation_name=$(index_path_to_name "$presentations_path")
  fi

  # write presentation index file
  file_append "$index_file_presentations" "  - [$presentation_name](./$presentations_path_relative)"
  file_append "$readme_file_presentations" "  - [$presentation_name](./$presentations_path_relative)"

  index_file_pages="$presentations_path/index.md"

  mkdir -p "$presentations_path/00_index/"
  teaser_for_presentation="$presentations_path/00_index/00_teaser.md"
  index_file_topics="$presentations_path/00_index/01_topics.md"

  index_file_init "$index_file_topics" 'Topics'
  ./app _build-presentation-index "$presentations_path" "$index_file_topics" "$parent_folder"

  index_file_init "$index_file_pages"
  ./app _build-presentations-index "$presentations_path" "$index_file_pages" $depth "$parent_folder"

  # concat README.md from page.md and index.md
  readme_for_index="$presentations_path/README.md"

  cat "$teaser_for_presentation" > "$readme_for_index"
  cat "$index_file_pages" >> "$readme_for_index"
done
