#!/bin/bash

#command-info: build index for the easy-presenter

source "$TERMINAL_PATH/app.bootstrap"

presentation_index_files="$EASY_PRESENTER_SOURCE/index.md"
pdf_index_file="$EASY_PRESENTER_SOURCE/index-pdfs.md"
readme_file_presentations="$EASY_PRESENTER_SOURCE/README.md"
parent_folder='.'
depth=0

file_clear "$presentation_index_files"
file_clear "$readme_file_presentations"
file_clear "$pdf_index_file"

index_file_init "$readme_file_presentations" "Präsentationen:"
index_file_init "$pdf_index_file" "Präsentationen:"

for presentation_path in "$EASY_PRESENTER_SOURCE"/*
do
  # if it is a file
  if [ -f "$presentation_path" ];
  then
    continue
  fi

  presentation_path_relative=$(basename "$presentation_path")

  possible_presentation_teaser_file="$presentation_path/00_index/00_teaser.md"
  if [ -f "$possible_presentation_teaser_file" ];
  then
    presentation_name=$(index_name_from_file "$possible_presentation_teaser_file")
  else
    presentation_name=$(file_path_to_name "$presentation_path")
  fi

  # write presentation index file
  file_append "$presentation_index_files" "  - [$presentation_name](./$presentation_path_relative)"

  file_append "$readme_file_presentations" "  - [$presentation_name](./$presentation_path_relative)"

  presentation_pdf_file_name=$(file_name_to_path "cw-wordpress-$presentation_path_relative.pdf")
  file_append "$pdf_index_file" "  - [$presentation_name (pdf)](./$presentation_path_relative/$presentation_pdf_file_name)"


  presentation_index_file="$presentation_path/index.md"

  mkdir -p "$presentation_path/00_index/"
  presentation_teaser_file="$presentation_path/00_index/00_teaser.md"
  index_file_topics="$presentation_path/00_index/01_topics.md"

  index_file_init "$index_file_topics" 'Kapitelübersicht'
  command_exec '_build-chapter-index' "$presentation_path" "$index_file_topics" "$parent_folder"

  index_file_init "$presentation_index_file"
  command_exec '_build-folder-index' "$presentation_path" "$presentation_index_file" $depth "$parent_folder"

  # concat README.md from page.md and index.md
  presentation_readme_file="$presentation_path/README.md"

  cat "$presentation_teaser_file" > "$presentation_readme_file"
  cat "$presentation_index_file" >> "$presentation_readme_file"
done
