#!/bin/bash

#command-info: print help

source "$TERMINAL_PATH/app.bootstrap"

orange 'Usage: ./app [command] [help|*]'
green 'Available commands:'

# list all available commands
for command in "$TERMINAL_APP_COMMAND_PATH"/*
do
  # print command info
  command_name=$(basename "$command")
  if [ ${command_name:0:1} != "_" ];
  then
    command_print_info $command
  fi

done

newline
